### ISSUE TITLE
Sindragosa - mystischer puffer/ice tomb

### ISSUE THREAD

**Issue by wowclassic1234** [gamefreedomgit/Frostmourne#2901]
The stack reset for the ice tomb is not working correctly in the last phase. 
On our server, stacks are discarded if there is a direct line of sight between the player, the boss and the Ice tomb at ANY DISTANCE from the Ice tomb, that is, the player could stand at a distance of 15-20-25 meters from the ice tomb and the player  And don't get a stack. - this bug. 

On the official server, if a player moved away from a ice tomb at a distance of a couple of meters, but at the same time maintained a direct line of sight between the boss and the ice, then the player continues to receive stacks. 

3 hour 40 min 00 sec
https://youtu.be/ptcopEAgCcU?t=13191

https://www.wowhead.com/wotlk/de/spell=70127/mystischer-puffer
https://www.wowhead.com/wotlk/npc=36853/sindragosa
https://www.wowhead.com/wotlk/spell=69712/ice-tomb

**Comment by Aitirn** [comment]
Another wrong report by you. It's not because of the distance or the buffet, that bug is already fixed. Wherever you are, as long as you are behind the tomb, you won't get stacks, but the problem is you shouldn't be able to cast spells, which you can.  I will repeat that the bug is already fixed.

**Comment by wowclassic1234** [comment]
ok close

**Comment by wowclassic1234** [comment]
> Another wrong report by you. It's not because of the distance or the buffet, that bug is already fixed. Wherever you are, as long as you are behind the tomb, you won't get stacks, but the problem is you shouldn't be able to cast spells, which you can. I will repeat that the bug is already fixed. Please stop the nonsense bug reports, they are awful.
> 
> ```
> Message: Core/Scripts (Icecrown Citadel):
> 
> Sindragosa:
>  - Fixed players being able to melee and cast spells through Ice Tombs when targeting the boss.
> ```

**Comment by wowclassic1234** [comment]
>  but the problem is you shouldn't be able to cast spells, which you can. > 

Are you sure? Your information looks like fake.
I don't hit the boss or use any abilities, but I keep my distance from the tomb and still get a stack.

The second point
Priest stands at distance from tomb, while not using spells, you can see from the animation, but still gets a stack. 


https://youtu.be/Imtag0HMGFw?t=6251

**Comment by Aitirn** [comment]
As long as you are behind the tomb to reset your stacks, you are unable to cast spells. This is the correct functionality, if you can cast, you gain the stacks.

**Comment by wowclassic1234** [comment]
https://www.wowhead.com/blue-tracker/topic/us/sindragosa-ice-tomb-los-1673573

**Comment by wowclassic1234** [comment]
> As long as you are behind the tomb to reset your stacks, you are unable to cast spells. This is the correct functionality, if you can cast, you gain the stacks.

Here's a video I found just for you to let you know you don't understand the mechanics.

The hunter is standing at a distance from the tomb and shooting at it, there is line of sight between the hunter, the tomb and the boss, but the stacks on him are still updating, in the raid footage you can see how all three hunters have updated the debuff. So I can tell you with 100% certainty that the distance from the tomb should affect the debuff. This worked in 2010 and worked in 2023 wotlk classic.

https://youtu.be/LVcWZ5hfhis?t=482

**Comment by Aitirn** [comment]
On the video you sent, no hunter is behind tomb, they are near tomb left or right, ofc stacks will grow, stop with ur bs reports

**Comment by wowclassic1234** [comment]
> On the video you sent, no hunter is behind tomb, they are near tomb left or right, ofc stacks will grow, stop with ur bs reports

![Image](https://github.com/user-attachments/assets/e08238c2-8c4d-435a-b8c5-0665053d4e2e)

![Image](https://github.com/user-attachments/assets/fdca5eb6-a133-4440-b194-3cfb93a27144)

**Comment by wowclassic1234** [comment]
I'm waiting for the next comment that I drew this in Photoshop.

**Comment by wowclassic1234** [comment]
> На видео, которое вы прислали, за гробницей нет охотников, они находятся слева или справа от гробницы, конечно, стопки будут расти, прекратите писать чушь

Do you need glasses or can you figure it out without them?

https://youtu.be/MzNHD39y93M?t=386

![Image](https://github.com/user-attachments/assets/cf7ab462-2305-4975-bb66-10174b0675fd)

![Image](https://github.com/user-attachments/assets/3381a71a-a3fc-46dd-bda3-9317ad4e9287)

![Image](https://github.com/user-attachments/assets/c911ff08-b875-4048-8321-4b988745e5c7)

**Comment by Piootrek** [comment]
It works correctly.

**Comment by wowclassic1234** [comment]
> It works correctly.

This is not working correctly.

Compare the video, do you see that if a person stands at a distance of 2-4 meters from the ice tomb, then he continues to receive a stack? 

Wotlk 2010
https://youtu.be/MzNHD39y93M?t=386

Wotlk classic 2023
https://youtu.be/Imtag0HMGFw?t=6251

Whitemane
https://youtu.be/jQiJWqjJ1CA?t=6121

Look at your server, see? The player does not receive a stack when he is in the distance. This is a mistake. 

Players must run to each ice tomb to get rid of the stacks. This is not required on our server.
