### ISSUE TITLE
Chromie in H CoS

### ISSUE THREAD

**Issue by Aeradel** [gamefreedomgit/Frostmourne#967]
Chromie has had a rare habit of being stuck in the air at the ending after the boss is killed, preventing players from turning in the quest.

It is not presented to me as such, but if I move Chromie the issue is resolved for the players.

**Comment by UltraNix** [comment]
Fixed.

**Comment by Aeradel** [comment]
If this was fixed it was not pushed as this is still not working.

**Comment by WhitemaneIsa** [comment]
@UltraNix

**Comment by Exorcista** [comment]
![image](https://github.com/gamefreedomgit/Frostmourne/assets/6818405/38eeaacf-88fe-4264-83c6-e4a93e569ad7)

still happening xddd

**Comment by Greywolf59** [comment]
Damn, you were faster lol

**Comment by Greywolf59** [comment]
Happens in normal too.

**Comment by UltraNix** [comment]
@Greywolf59 @Exorcista Please - retest it.

**Comment by WhitemaneChronus** [comment]
As of today players are still facing this issue

**Comment by UltraNix** [comment]
I give up with this one :)

**Comment by Greywolf59** [comment]
Well there is definitely one change. For me on Heroic it worked now. Her arrival was  bit wobbly. However the biggest change is that drakonkin spawning from portals are stacked on each other in some instances.

**Comment by WhitemaneChronus** [comment]
@UltraNix From some experience in Cataclysm, some NPCs "cant" land because player is standing in their position, like [Atramedes](https://www.wowhead.com/es/npc=41442/atramedes) in BWD. or a few dungeon bosses had the same issue. but those will be fixed if players move out because i assume they continuously try to fly down. but i think chromie stops doing so after she gets out of dragon form. 
just a little assumption im not sure if it helps D:

**Comment by Aeradel** [comment]
Seems like I haven't had reported instances of this on Heroic anymore, but it is still happening in Normal.

**Comment by Riztazz** [comment]
Fixed, will close it's live

**Comment by Riztazz** [comment]
Gonna leave this issue open for a bit, lemme know if it happens again please

**Comment by Riztazz** [comment]
I'll take that as fixed:P
